language: perl
perl:
    - "5.23"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

os:
    - linux
    - osx

sudo: required

before_install:
    - wget http://search.cpan.org/CPAN/authors/id/M/MI/MIYAGAWA/Menlo-1.9001.tar.gz
    - tar -xzvf Menlo-1.9001.tar.gz
    - cd Menlo-1.9001
    - perl Makefile.PL
    - make
    - make test
    - sudo make install
