language: perl
perl:
    - "5.23"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"

os:
    - linux
    - osx

sudo: required

before_install:
    - curl -L https://cpanmin.us/ -o cpanm
    - chmod +x cpanm
    - sudo mv cpanm /usr/bin
